### ISSUE TITLE
Language code inconsistencies

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/le-utils#23]
While working on the [youtube subs for the TE chef](https://github.com/fle-internal/te-sushi-chef/pull/5/files#diff-6a44712e214d65c7d57dc60239e66309R207), @divad12 noticed inconsistencies in the short language codes defined in `le_utils/resources/languagelookup.json`. There is a mix of two letter codes like `pt-BR` and three letter codes `zul`.

The conventions are consistent between chefs, cc server, and kolibri, but loading data from external sources can be problematic. For example, a youtube video can provide subtitles for Zulu as `zu` but we need to upload them as `zul` to the cc server so that Kolibri will recognize them.

Should we consider standardizing on two letter codes? Possibly with a fallback/retro-compatible mode for three letter codes? (sidequestion: What is the `ka_name` used for?)

A change to two-letter codes will require revisiting:

  - [le_utils](https://github.com/learningequality/le-utils/blob/master/le_utils/resources/languagelookup.json)
  - Existing chefs
  - Existing content channels in the content-curation server
  - [Frontend code](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/media_player/assets/src/views/languagelookup.js)
  - Other places?

**Comment by jayoshih** [comment]
I'm really hesitant on changing the language codes because the language code is used as the model id. Changing the language codes could then break the content that uses 3-letter codes as the corresponding id would no longer exist. Also, certain languages have 3-letter codes because the 2-letter representation has been taken (e.g. Finnish and Filipino), so I'm not sure how cleanly certain languages will be translated to a new 2-letter scheme. An alternative solution could be to update the `getlang` method to look for a "closest match" or have some sort of mapping from 2-letter codes to 3-letter codes

**Comment by jayoshih** [comment]
@aronasorman Might be good to get your opinion on this too

**Comment by rtibbles** [comment]
I think having an API is a good approach, however, I would urge you both to consider that both the data and the API should be accessible from both Python and Javascript, as we will need all of this language data during content render to make decisions about text directionality within content renderers.

**Comment by rtibbles** [comment]
Also, for even more languages, c.f. https://www.ethnologue.com/

**Comment by ivanistheone** [comment]
Fixed in https://github.com/learningequality/le-utils/pull/28
